# Config file for air
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o bin/server ./cmd/"
  bin = "bin/server"
  full_bin = "APP_ENV=dev bin/server"
  include_ext = ["go", "mod", "sum", "html"]
  exclude_dir = ["node_modules", "sql", "bin", "src"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  follow_symlink = true
  delay = 1000
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500 # nanosecond
  rerun = false
  rerun_delay = 500

[log]
  level = "debug"
  color = "true"
  timestamp = "true"

[misc]
  clean_on_exit = true
