# Config file for air
[build]
  cmd = "go build -o bin/server ./cmd/"
  bin = "bin/server"
  full_bin = "APP_ENV=dev bin/server"
  include_ext = ["go", "mod", "sum", "html", "js", "css"]
  exclude_dir = ["node_modules", "sql", "bin", "src"]
  exclude_file = ["air.toml"]
  follow_symlink = true
  delay = 1000

[log]
  level = "debug"
  color = "true"
  timestamp = "true"

[serve]
  watch_dir = ["."]
  watch_ext = ["go", "mod", "sum", "html", "js", "css"]
  watch_delay = 200
  grace_period = 1000
  full_bin = "APP_ENV=dev bin/server"
  check_interval = 500
  kill_signal = "SIGTERM"
  kill_timeout = 1000
